on:
  push:
  pull_request:

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # ou a versão que atende às necessidades do seu projeto

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        uses: icrawl/action-eslint@v1
        with:
          custom-glob: apps # ajuste conforme necessário
