name: Code Quality Check

# Disparar em push, PR, ou manualmente
on:
  push:
    branches:
      - main
      - '**/*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: ESLint and Prettier Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Define projects
        id: define-projects
        run: |
          echo "PROJECTS=1_calculadora/calculadora" >> $GITHUB_ENV

      - name: Run lint and prettier checks
        run: |
          for project in $PROJECTS; do
            echo "Processing project: $project"
            cd $project
            npm install
            npm run lint
            # Prettier check, ignore exit code
            npm run prettier:check || true
            cd ..
          done
        shell: /usr/bin/bash -e {0}
        env:
          PROJECTS: ${{ env.PROJECTS }}

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Define projects
        id: define-projects
        run: |
          echo "PROJECTS=1_calculadora/calculadora" >> $GITHUB_ENV

      - name: Run tests
        run: |
          for project in $PROJECTS; do
            echo "Processing project: $project"
            cd $project
            npm install
            npm test
            cd ..
          done
        shell: /usr/bin/bash -e {0}
        env:
          PROJECTS: ${{ env.PROJECTS }}